
package sj_calculator;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shivam jaiswal
 */
public class BMI_Calc extends javax.swing.JFrame {

    /**
     * Creates new form BMI_Calc
     */
    public BMI_Calc() {
        initComponents();
        jLabel_down.setVisible(false);
        jLabel_up.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Heading = new javax.swing.JLabel();
        jLabel_mtr = new javax.swing.JLabel();
        jLabel_KG = new javax.swing.JLabel();
        jTextField_KG = new javax.swing.JTextField();
        jTextField_mtr = new javax.swing.JTextField();
        jButton_Calculate = new javax.swing.JButton();
        jLabel_up = new javax.swing.JLabel();
        jLabel_down = new javax.swing.JLabel();
        jLabel_warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Result = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel_Heading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Heading.setText("BMI Calculator");

        jLabel_mtr.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel_mtr.setText("Enter Height in mtr.");

        jLabel_KG.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel_KG.setText("Enter Weight in Kg.");

        jTextField_KG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_KGActionPerformed(evt);
            }
        });
        jTextField_KG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_KGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KGKeyTyped(evt);
            }
        });

        jTextField_mtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mtrActionPerformed(evt);
            }
        });
        jTextField_mtr.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField_mtrPropertyChange(evt);
            }
        });
        jTextField_mtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_mtrKeyTyped(evt);
            }
        });

        jButton_Calculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Calculate.setText("Calculate");
        jButton_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalculateActionPerformed(evt);
            }
        });

        jLabel_up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_up.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_up.setText("*");

        jLabel_down.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_down.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_down.setText("*");

        jLabel_warning.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel_warning.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Your BMI :");

        jLabel_Result.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        jLabel4.setText("©  Shivam Jaiswal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel_KG, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_KG, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_up))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_mtr)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_mtr, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_down))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel_Heading)
                            .addGap(75, 75, 75)))
                    .addComponent(jLabel4))
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_KG, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_KG, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel_up, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_mtr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_mtr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_down))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalculateActionPerformed
        jLabel_up.setVisible(false);
        jLabel_down.setVisible(false);

        if (jTextField_KG.getText().equals("")) {
            jLabel_up.setVisible(true);
            jLabel_warning.setText("Enter the value in space");
            jLabel_warning.setVisible(true);

        }
        if (jTextField_mtr.getText().equals("")) {
            jLabel_down.setVisible(true);
            jLabel_warning.setText("Enter the value in space");
            jLabel_warning.setVisible(true);
        } else {
            jLabel_warning.setText("");
            try{
            double kg = Double.parseDouble(jTextField_KG.getText());
            double ht = Double.parseDouble(jTextField_mtr.getText());
            double ans =  Math.round( kg/(ht*ht) * 100.0) / 100.0 ;
            if(ans <18.5)
            jLabel2.setText("Underweight");
            else if(ans > 18.5 && ans < 24.90)
            jLabel2.setText("Healthy weight");
            else if(ans > 25 && ans < 29.9)
            jLabel2.setText("Overweight");
            else
            jLabel2.setText("Obese");
            jLabel_Result.setText(String.valueOf(ans));
            }catch(Exception ex){
                JFrame f= new JFrame();
                JOptionPane.showMessageDialog(f, "Check Input in the field!", "Oopss..", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_CalculateActionPerformed

    private void jTextField_mtrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_mtrKeyTyped
        if(!(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()== '.')){
            jLabel_warning.setText("Enter Only Digit");
            jLabel_warning.setVisible(true);
            evt.consume();
        }else{
            jLabel_warning.setText("");
        }
    }//GEN-LAST:event_jTextField_mtrKeyTyped

    private void jTextField_mtrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField_mtrPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mtrPropertyChange

    private void jTextField_mtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mtrActionPerformed

    private void jTextField_KGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KGKeyTyped
        if(!(Character.isDigit(evt.getKeyChar())  || evt.getKeyChar()== '.')){
            jLabel_warning.setText("Enter Only Digit");
            jLabel_warning.setVisible(true);
            evt.consume();
        }else{
            jLabel_warning.setText("");
            //jLabel_Result.setVisible(false);
        }
    }//GEN-LAST:event_jTextField_KGKeyTyped

    private void jTextField_KGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KGKeyReleased

    }//GEN-LAST:event_jTextField_KGKeyReleased

    private void jTextField_KGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_KGActionPerformed

    }//GEN-LAST:event_jTextField_KGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Calculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Heading;
    private javax.swing.JLabel jLabel_KG;
    private javax.swing.JLabel jLabel_Result;
    private javax.swing.JLabel jLabel_down;
    private javax.swing.JLabel jLabel_mtr;
    private javax.swing.JLabel jLabel_up;
    private javax.swing.JLabel jLabel_warning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_KG;
    private javax.swing.JTextField jTextField_mtr;
    // End of variables declaration//GEN-END:variables
}
